# Generated by Django 5.2.7 on 2025-10-08 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_fr", models.CharField(max_length=255)),
                ("name_ar", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="A unique, URL-friendly name for the category.",
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="A hex color code for the category, e.g., #FF5733.",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=0,
                        help_text="An integer to determine the order of categories.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["weight", "name_fr"],
            },
        ),
    ]
