# Generated by Django 5.2.7 on 2025-10-08 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "locale",
                    models.CharField(
                        choices=[("ar", "Arabic"), ("fr", "French")], max_length=2
                    ),
                ),
                ("rtl", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("body", models.TextField()),
                ("featured", models.BooleanField(default=False)),
                ("reading_time_min", models.IntegerField(default=0)),
                ("publish_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, null=True)),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("source_urls", models.JSONField(blank=True, null=True)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("storage_url", models.URLField()),
                (
                    "alt_text_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alt_text_ar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("caption_fr", models.TextField(blank=True, null=True)),
                ("caption_ar", models.TextField(blank=True, null=True)),
                ("credit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("cc_by", "Creative Commons BY"),
                            ("cc_by_sa", "Creative Commons BY-SA"),
                            ("all_rights_reserved", "All Rights Reserved"),
                        ],
                        default="internal",
                        max_length=50,
                    ),
                ),
                ("focal_point", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_fr", models.CharField(max_length=255)),
                ("name_ar", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "governorate_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "region_type",
                    models.CharField(
                        choices=[
                            ("governorate", "Governorate"),
                            ("municipality", "Municipality"),
                            ("national", "National"),
                        ],
                        default="governorate",
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "coordinates",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_fr", models.CharField(max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
